version: '3'

services:

  samba:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: 'Europe/Madrid'
    ports:
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /mnt/samba:/mnt
    command: '-s "User Volume;/mnt;yes;no;no;user" -u "user;mypasswd*" -p'

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "192.168.1.5:53:53/tcp"
      - "192.168.1.5:53:53/udp"
      - "67:67/udp"
      - "8888:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: 'passwd'  #'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
       - '/mnt/config/etc-pihole/:/etc/pihole/'
       - '/mnt/config/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - /mnt/config/config-jellyfin:/config
      - /mnt/config/cache-jellyfin:/cache
      - /mnt/samba/Videos:/media
        #- /mnt/samba/Series:/media2:ro
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://dmedia.myhome.ex

  flexget:
    image: wiserain/flexget
    container_name: flexget
    restart: on-failure:5
    ports :
      - 5050:5050
    volumes:
      - /mnt/config/config-flexget:/config
      - /mnt/samba/torrents:/downloads
      - /mnt/samba/Videos/Pelis
      - /mnt/samba/Videos/Series
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - FG_WEBUI_PASSWD=passwd
    volumes:
      - /mnt/config/config-flexget:/config

  proxy:
    image: traefik:v2.4         # Review traefik documentation https://doc.traefik.io/traefik/
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:8090
    ports:
      - 8090:8090
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: vpn
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=sdfgsdfg@mail.com     # Required
      - "PASS=sdfgsdfgsdfg"         # Required
      - CONNECT=France
      - TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
  torrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: torrent
    network_mode: container:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8090
    labels:
      - traefik.enable=true
      - traefik.http.services.torrent.loadbalancer.server.port=8090
      - traefik.http.routers.torrent.rule=Host(`hostname`)
    depends_on:
      - vpn

# Make sure that custom-host resolves to the ip address of the server
# for example /etc/hosts contains 127.0.0.1  custom-host
# the torrent service would be available at http://custom-host
