version: "3.3"

services:

  plex:
    image: linuxserver/plex
    container_name: plex
    ports: 
      - "8200:32400" 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - VERSION=docker
    volumes:
      - ./config:/config
      - /mnt/DATOS/Videos/Series:/tv
      - /mnt/DATOS/Videos/Peliculas:/movies
    restart: unless-stopped
